FeeSystem/Controllers/PaymentController.cs
using FeeSystem.Logic;
using FeeSystem.Models;
using FeeSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Security.Claims;

namespace FeeSystem.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPaymentHistoryRepository _paymentHistoryRepository;
        private readonly IResidentRepository _residentRepository;

        public PaymentController(IPaymentHistoryRepository paymentHistoryRepository, IResidentRepository residentRepository)
        {
            _paymentHistoryRepository = paymentHistoryRepository;
            _residentRepository = residentRepository;
        }
        public IActionResult Transfer(int paymentHistoryId)
        {
            var paymentHistory = _paymentHistoryRepository.GetPaymentHistoryById(paymentHistoryId);
            var resident = _residentRepository.TakeResidentById(paymentHistory.ConnectedResident.Id);
            return View((resident, paymentHistory.PaymentDetails()));
        }
        public IActionResult Create()
        {
            /*var residents = _residentRepository.ReturnAllResidents();
            (PaymentHistory, IEnumerable<Resident>) model = (null, residents);
            */
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PaymentHistory paymentHistory)
        {
            if (ModelState.IsValid)
            {
                _paymentHistoryRepository.AddPayment(paymentHistory);
                return RedirectToAction("Index", "Home");
            }
            //(PaymentHistory, IEnumerable<Resident>) model = (null, null);
            return View(paymentHistory);
        }

        public IActionResult Edit(int Id)
        {
            var payment = _paymentHistoryRepository.GetPaymentHistoryById(Id);
            if (payment == null)
                return NotFound();

            return View(payment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(PaymentHistory paymentHistory)
        {
            if (ModelState.IsValid)
            {
                _paymentHistoryRepository.EditPayement(paymentHistory);
                return RedirectToAction("Index", "Home");
            }
            return View(paymentHistory);
        }

        public IActionResult Delete(int Id)
        {
            var payment = _paymentHistoryRepository.GetPaymentHistoryById(Id);
            if (payment == null)
                return NotFound();

            return View(payment);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int Id)
        {
            var payment = _paymentHistoryRepository.GetPaymentHistoryById(Id);
            _paymentHistoryRepository.DeletePayment(payment);

            return RedirectToAction("Index", "Home");
        }
    }
}

FeeSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/content/site.css" rel="stylesheet" />
    <link href="~/content/login.css" rel="stylesheet" />
    <link href="~/content/payment-details.css" rel="stylesheet" />
    <link href="~/content/residents-panel.css" rel="stylesheet" />
    <link href="~/content/my-buttons.css" rel="stylesheet" />

    <title>@ViewBag.Title</title>
</head>
<body>

    <nav class="fixed-top navbar-expand-lg navbar-dark bg-dark">

        <div class="collapse navbar-collapse">

            @if (SignInManager.IsSignedIn(User))
            {
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">System opłat</a></li>

                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a class="nav-link text-decoration-none" asp-controller="Home" asp-action="Create">Dodaj lokatora</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-decoration-none" asp-controller="Payment" asp-action="Create">Dodaj płatność</a>
                    </li>
                }
                else
                {
                    <a class="nav-link" asp-controller="Home" asp-action="History">Historia</a>
                }
            </ul>
                <form asp-controller="Account" asp-action="Logout" id="logoutForm" method="post">
                    <ul class="m-0 p-0">
                        <li class="nav-link text-warning">@User.Identity.Name <a class="text-decoration-none" href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a></li>

                    </ul>
                </form>
            }
            else
            {
                <ul class="nav navbar-nav">
                    <li><a id="registerLink" asp-controller="Account" asp-action="Register" class="nav-link">Rejestruj</a></li>
                    <li><a id="loginLink" asp-controller="Account" asp-action="Login" class="nav-link">Zaloguj</a></li>

                </ul>
            }

        </div>
    </nav>

    <div class="container body-content">
        <div class="row mt-5 ">
            @RenderBody()

        </div>
        <footer class="d-flex justify-content-center">2019 &copy; System Opłat we Wspólnocie Mieszkaniowej - Patryk Binicki</footer>
    </div>
    
    <script src="~/scripts/select-bank.js"></script>
</body>
</html>